//! Stable typed identifiers.
//!
//! - [`ProjectId`] is a **UUIDv7** (canonical hyphenated string). It names the project's
//!   folder in the engine-side project store (`<projects_root>/<uuid>/project.ether`).
//! - Every other entity ID is a **ULID** (26-char Crockford base32 string). Both are
//!   time-ordered 128-bit IDs; entity IDs stay ULIDs because they are shorter on the wire.
//!
//! Every entity in the document is addressed by a typed ID, never by an index. IDs are
//! generated by whoever *creates* the entity: usually the UI (so commands are idempotent and
//! optimistic UI / future CRDT sync work), sometimes the controller (e.g. children of a
//! duplicated track). On the wire and in `.ether` files they are 26-char Crockford base32
//! ULID strings; in TypeScript they are `string` aliases.
//!
//! No randomness source is used implicitly (so the crate stays wasm-safe without
//! `getrandom`): hosts seed an [`IdGen`] with entropy and a clock.

use std::fmt;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use ts_rs::TS;
pub use ulid::Ulid;

/// Common behaviour of all typed IDs.
pub trait Id: Copy + Eq + Ord + std::hash::Hash + fmt::Debug + fmt::Display {
    /// Short entity name used in debug output and error messages (e.g. `"Track"`).
    const KIND: &'static str;
    fn from_ulid(ulid: Ulid) -> Self;
    fn ulid(self) -> Ulid;
}

macro_rules! define_ids {
    ($($(#[$meta:meta])* $name:ident => $kind:literal;)*) => {$(
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, TS)]
        pub struct $name(#[ts(type = "string")] pub Ulid);

        impl Serialize for $name {
            fn serialize<S: serde::Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                let mut buf = [0u8; ulid::ULID_LEN];
                s.serialize_str(self.0.array_to_str(&mut buf))
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: serde::Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let s = <std::borrow::Cow<'de, str>>::deserialize(d)?;
                Ulid::from_string(&s).map(Self).map_err(serde::de::Error::custom)
            }
        }

        impl Id for $name {
            const KIND: &'static str = $kind;
            fn from_ulid(ulid: Ulid) -> Self { Self(ulid) }
            fn ulid(self) -> Ulid { self.0 }
        }

        impl $name {
            /// The all-zero ID. Only meaningful as a sentinel in tests.
            pub const NIL: Self = Self(Ulid::nil());
        }

        impl fmt::Debug for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                write!(f, "{}({})", $kind, self.0)
            }
        }

        impl fmt::Display for $name {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
                fmt::Display::fmt(&self.0, f)
            }
        }

        impl FromStr for $name {
            type Err = ulid::DecodeError;
            fn from_str(s: &str) -> Result<Self, Self::Err> { Ulid::from_string(s).map(Self) }
        }
    )*};
}

define_ids! {
    /// A track (audio, MIDI, group, return or master).
    TrackId => "Track";
    /// A clip, in the arrangement or in a session slot.
    ClipId => "Clip";
    /// A MIDI note inside a clip.
    NoteId => "Note";
    /// A device instance (built-in or plugin) on a track's device chain.
    DeviceId => "Device";
    /// A send from a track to a return track.
    SendId => "Send";
    /// A session-view scene (row).
    SceneId => "Scene";
    /// An automation lane (arrangement lane on a track, or a clip envelope).
    AutomationLaneId => "AutomationLane";
    /// A breakpoint in an automation lane.
    AutomationPointId => "AutomationPoint";
    /// A point of the tempo map.
    TempoPointId => "TempoPoint";
    /// A time-signature change.
    TimeSignatureId => "TimeSignature";
    /// A warp marker of an audio clip.
    WarpMarkerId => "WarpMarker";
    /// An imported media file (audio sample) referenced by clips and samplers.
    MediaId => "Media";
}

/// Identifies a project (stable across saves, renames and machines). UUIDv7.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, TS)]
pub struct ProjectId(#[ts(type = "string")] pub uuid::Uuid);

impl ProjectId {
    pub const NIL: Self = Self(uuid::Uuid::nil());

    /// Build a UUIDv7 from Unix-epoch milliseconds and 10 random bytes.
    pub fn v7(now_ms: u64, random: [u8; 10]) -> Self {
        Self(uuid::Builder::from_unix_timestamp_millis(now_ms, &random).into_uuid())
    }
}

impl fmt::Debug for ProjectId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Project({})", self.0)
    }
}

impl fmt::Display for ProjectId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        fmt::Display::fmt(&self.0.hyphenated(), f)
    }
}

impl FromStr for ProjectId {
    type Err = uuid::Error;
    fn from_str(s: &str) -> Result<Self, Self::Err> {
        uuid::Uuid::parse_str(s).map(Self)
    }
}

/// Deterministic, monotonic ULID generator (also mints UUIDv7 project ids).
///
/// Hosts construct it with a seed from their entropy source (`getrandom` natively,
/// `crypto.getRandomValues` on the web) and pass the current wall-clock time in milliseconds
/// on each call. Within the same millisecond the random part is incremented, so IDs from one
/// generator are strictly increasing.
#[derive(Debug, Clone)]
pub struct IdGen {
    state: u64,
    last: Ulid,
}

impl IdGen {
    pub fn new(seed: u64) -> Self {
        Self {
            state: seed | 1,
            last: Ulid::nil(),
        }
    }

    fn next_u64(&mut self) -> u64 {
        // xorshift64*: not cryptographic, only needs to avoid collisions between peers.
        let mut x = self.state;
        x ^= x >> 12;
        x ^= x << 25;
        x ^= x >> 27;
        self.state = x;
        x.wrapping_mul(0x2545_F491_4F6C_DD1D)
    }

    /// Generate a raw ULID for time `now_ms` (Unix epoch milliseconds).
    pub fn next_ulid(&mut self, now_ms: u64) -> Ulid {
        let ms = now_ms.max(self.last.timestamp_ms());
        let candidate = if ms == self.last.timestamp_ms() && !self.last.is_nil() {
            self.last
                .increment()
                .unwrap_or_else(|| Ulid::from_parts(ms + 1, 0))
        } else {
            let random =
                ((self.next_u64() as u128) << 64 | self.next_u64() as u128) & ((1u128 << 80) - 1);
            Ulid::from_parts(ms, random)
        };
        self.last = candidate;
        candidate
    }

    /// Generate a typed ID.
    pub fn next<I: Id>(&mut self, now_ms: u64) -> I {
        I::from_ulid(self.next_ulid(now_ms))
    }

    /// Generate a UUIDv7 project id.
    pub fn next_project_id(&mut self, now_ms: u64) -> ProjectId {
        let a = self.next_u64().to_le_bytes();
        let b = self.next_u64().to_le_bytes();
        let mut random = [0u8; 10];
        random[..8].copy_from_slice(&a);
        random[8..].copy_from_slice(&b[..2]);
        ProjectId::v7(now_ms, random)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn ids_are_monotonic_and_roundtrip() {
        let mut g = IdGen::new(42);
        let a: TrackId = g.next(1_000);
        let b: TrackId = g.next(1_000);
        let c: TrackId = g.next(999);
        assert!(a < b && b < c);
        let json = serde_json::to_string(&a).unwrap();
        assert_eq!(json.len(), 28); // 26 chars + quotes
        let back: TrackId = serde_json::from_str(&json).unwrap();
        assert_eq!(a, back);
        assert_eq!(a.to_string().parse::<TrackId>().unwrap(), a);

        let p = g.next_project_id(1_700_000_000_000);
        assert_eq!(p.0.get_version_num(), 7);
        let json = serde_json::to_string(&p).unwrap();
        assert_eq!(json.len(), 38); // 36-char hyphenated + quotes
        assert_eq!(serde_json::from_str::<ProjectId>(&json).unwrap(), p);
        assert_eq!(p.to_string().parse::<ProjectId>().unwrap(), p);
    }
}
