[package]
name = "ether-controller"
description = "Controller: commands to ops to model to patches; model to render snapshot."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
