[package]
name = "ether-plugin-scanner"
description = "Out-of-process CLAP plugin scanner binary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]

[lints]
workspace = true
