// Types of the wasm-bindgen output (apps/web/src/wasm/pkg, generated by
// scripts/build-wasm.mjs and git-ignored). Declared here so `tsc` works without a wasm
// build; keep in sync with the #[wasm_bindgen] exports of crates/ether-wasm/src/web.rs.

declare module "@ether-wasm/ether_wasm.js" {
  export interface InitOutput {
    readonly memory: WebAssembly.Memory;
  }
  export function initSync(opts: { module: WebAssembly.Module }): InitOutput;

  /** Synchronous file system the controller uses (see ../engine/syncFs.ts). */
  export interface JsFsHost {
    read(path: string): Uint8Array;
    write(path: string, bytes: Uint8Array): void;
    rename(from: string, to: string): void;
    /** JSON `[{ name, is_dir, size, modified_ms }]`. */
    list(dir: string): string;
    mkdir(path: string): void;
    remove(path: string): void;
    /** JSON entry or `null`. */
    stat(path: string): string;
  }

  export class WasmController {
    constructor(
      seed: bigint,
      sampleRate: number,
      control: SharedArrayBuffer,
      reports: SharedArrayBuffer,
      fs: JsFsHost,
    );
    handle(messageJson: string): string;
    tick(nowMs: number): string;
    pending_control_bytes(): number;
    engine_blocks(): number;
    free(): void;
  }

  export class WasmEngine {
    constructor(sampleRate: number, control: SharedArrayBuffer, reports: SharedArrayBuffer);
    process(frames: number): void;
    output_ptr(channel: number): number;
    blocks(): number;
    free(): void;
  }

  /** Graph snapshot costs of the large fixture (JSON `SnapshotCosts`, ms; web-perf). */
  export function bench_graph_snapshot(runs: number): string;
}

declare module "@ether-wasm/ether_wasm_bg.wasm?url" {
  const url: string;
  export default url;
}
