//! Filter magnitude responses shared by the engine's EQ-style devices and the UI's `EqCurve`
//! widget (v0.2, frozen by contracts-3; UI mirror owned by `graphical-eq`, CONTRACTS.md
//! §12.15).
//!
//! Every shape is a Simper TPT state-variable filter (`ether_devices::dsp::svf`, the EQ's
//! filter): `y = m0·x + m1·band + m2·low` with coefficients from [`svf_coefs`]. Its exact
//! digital magnitude at `f` is the analog prototype `|m0 + (m1·s + m2) / (s² + k·s + 1)|`
//! evaluated at `s = j·tan(π·f/fs) / g` (the bilinear transform is exact for the TPT
//! structure). `*24` shapes are two identical 12 dB/oct stages (magnitude squared).
//!
//! The UI mirrors [`svf_coefs`] and [`magnitude_db`] exactly
//! (`ui/src/features/devices/layout/eq/eqResponse.ts`, checked against
//! `crates/ether-protocol/tests/fixtures/eq_response_vectors.json`, regenerated by
//! `UPDATE_EQ_VECTORS=1 cargo test -p ether-protocol --test eq_response`).

use std::f64::consts::PI;

use serde::{Deserialize, Serialize};
use ts_rs::TS;

/// Filter shapes (append-only).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, TS)]
pub enum EqShape {
    /// 12 dB/oct high-pass.
    LowCut,
    LowShelf,
    Bell,
    Notch,
    HighShelf,
    /// 12 dB/oct low-pass.
    HighCut,
    /// 24 dB/oct high-pass (two stages).
    LowCut24,
    /// 24 dB/oct low-pass (two stages).
    HighCut24,
    /// Band-pass, unity gain at the centre.
    BandPass,
}

/// SVF coefficients (see the module docs).
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct SvfCoefs {
    pub g: f64,
    pub k: f64,
    pub m0: f64,
    pub m1: f64,
    pub m2: f64,
}

/// Coefficients of one stage of `shape` at `freq` Hz, `gain_db` (shelves, bell) and `q`.
/// Identical to the EQ device's `Coefs::new` (cutoff clamped to `1..=0.49·fs`, `q >= 0.01`).
pub fn svf_coefs(shape: EqShape, freq: f64, gain_db: f64, q: f64, sample_rate: f64) -> SvfCoefs {
    let fc = freq.clamp(1.0, sample_rate * 0.49);
    let g = (PI * fc / sample_rate).tan();
    let q = q.max(0.01);
    let k = 1.0 / q;
    let a = 10f64.powf(gain_db / 40.0);
    let c = |g, k, m0, m1, m2| SvfCoefs { g, k, m0, m1, m2 };
    match shape {
        EqShape::LowCut | EqShape::LowCut24 => c(g, k, 1.0, -k, -1.0),
        EqShape::HighCut | EqShape::HighCut24 => c(g, k, 0.0, 0.0, 1.0),
        EqShape::Notch => c(g, k, 1.0, -k, 0.0),
        EqShape::BandPass => c(g, k, 0.0, k, 0.0),
        EqShape::Bell => {
            let k = 1.0 / (q * a);
            c(g, k, 1.0, k * (a * a - 1.0), 0.0)
        }
        EqShape::LowShelf => c(g / a.sqrt(), k, 1.0, k * (a - 1.0), a * a - 1.0),
        EqShape::HighShelf => c(g * a.sqrt(), k, a * a, k * (1.0 - a) * a, 1.0 - a * a),
    }
}

/// Linear magnitude of one SVF stage at `at_hz`.
pub fn svf_magnitude(c: &SvfCoefs, at_hz: f64, sample_rate: f64) -> f64 {
    let f = at_hz.clamp(0.0, sample_rate * 0.4999);
    let w = (PI * f / sample_rate).tan() / c.g;
    // s = j·w: s² = -w², so the denominator is (1 - w²) + j·k·w.
    let (dr, di) = (1.0 - w * w, c.k * w);
    // Numerator m0·(s² + k·s + 1) + m1·s + m2 = (m0·(1 - w²) + m2) + j·w·(m0·k + m1).
    let (nr, ni) = (c.m0 * (1.0 - w * w) + c.m2, w * (c.m0 * c.k + c.m1));
    ((nr * nr + ni * ni) / (dr * dr + di * di)).sqrt()
}

/// Magnitude in dB of `shape` at `at_hz` (floored at -120 dB).
pub fn magnitude_db(
    shape: EqShape,
    freq: f64,
    gain_db: f64,
    q: f64,
    at_hz: f64,
    sample_rate: f64,
) -> f64 {
    let c = svf_coefs(shape, freq, gain_db, q, sample_rate);
    let mut m = svf_magnitude(&c, at_hz, sample_rate);
    if matches!(shape, EqShape::LowCut24 | EqShape::HighCut24) {
        m *= m;
    }
    (20.0 * m.max(1e-6).log10()).max(-120.0)
}

#[cfg(test)]
mod tests {
    use super::*;

    const FS: f64 = 48_000.0;

    #[test]
    fn landmark_values() {
        // Bell: +6 dB at the centre, flat far away.
        assert!((magnitude_db(EqShape::Bell, 1000.0, 6.0, 1.0, 1000.0, FS) - 6.0).abs() < 1e-9);
        assert!(magnitude_db(EqShape::Bell, 1000.0, 6.0, 1.0, 20.0, FS).abs() < 0.05);
        // Cuts: -3 dB (Q = 1/√2) at the cutoff, -12 dB/oct slope.
        let q = std::f64::consts::FRAC_1_SQRT_2;
        assert!((magnitude_db(EqShape::HighCut, 1000.0, 0.0, q, 1000.0, FS) + 3.0103).abs() < 1e-3);
        assert!(
            (magnitude_db(EqShape::LowCut24, 1000.0, 0.0, q, 1000.0, FS) + 6.0206).abs() < 1e-3
        );
        // Shelves reach their gain, half of it at the corner.
        assert!((magnitude_db(EqShape::LowShelf, 200.0, 12.0, q, 10.0, FS) - 12.0).abs() < 0.05);
        assert!((magnitude_db(EqShape::HighShelf, 5000.0, -6.0, q, 20000.0, FS) + 6.0).abs() < 0.2);
        // Notch and band-pass at the centre.
        assert!(magnitude_db(EqShape::Notch, 1000.0, 0.0, 2.0, 1000.0, FS) <= -119.0);
        assert!(magnitude_db(EqShape::BandPass, 1000.0, 0.0, 2.0, 1000.0, FS).abs() < 1e-9);
    }
}
