//! Track lifecycle and layout. Mixer controls are in [`crate::mixer`], recording/input in
//! [`crate::recording`].

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::model::{Color, TrackId, TrackKind};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS)]
#[serde(tag = "type")]
pub enum TrackCommand {
    /// Create a track with a client-chosen id, placed before `before` (None = last among its
    /// siblings), inside group `parent`. MIDI tracks get no default instrument (the UI
    /// follows up with `Device::Insert` in a `Batch` if it wants one).
    Create {
        id: TrackId,
        kind: TrackKind,
        name: Option<String>,
        color: Option<Color>,
        parent: Option<TrackId>,
        before: Option<TrackId>,
    },
    /// Deletes the track and everything on it (clips, notes, devices, sends to/from it,
    /// lanes). Children of a group are deleted too. The master track cannot be deleted.
    Delete {
        id: TrackId,
    },
    /// Deep copy placed right after the original; child entity ids are generated by the
    /// controller.
    Duplicate {
        id: TrackId,
        new_id: TrackId,
    },
    Rename {
        id: TrackId,
        name: String,
    },
    SetColor {
        id: TrackId,
        color: Color,
    },
    /// Reorder / regroup: `parent` = the destination group (`None` = top level), `before` a
    /// sibling there. Moving into/out of a group is this command (v0.2 `groups-buses` keeps
    /// it; the model rejects cycles and master/return/VCA tracks inside groups). Explicit
    /// outputs (`TrackOutput::Track`) are kept; `Default` follows the new parent.
    Move {
        id: TrackId,
        parent: Option<TrackId>,
        before: Option<TrackId>,
    },
    /// Set a MIDI track's piano-roll scale (undoable document edit; never restricts notes).
    SetScale {
        id: TrackId,
        scale: crate::model::TrackScale,
    },
    // --- v0.2 (`groups-buses`, CONTRACTS.md §12.10) ---
    /// Cmd+G: create group track `group` around `ids` (all with the same parent; nested
    /// groups allowed; master/return/VCA rejected). The group takes the position of the
    /// first of `ids` in track order; the tracks move inside it in their current order.
    /// `name: None` = "Group". One undo step; no other ids are minted.
    GroupSelected {
        ids: Vec<TrackId>,
        group: TrackId,
        name: Option<String>,
    },
    /// Move a group's children to the group's parent at its position (order kept) and
    /// delete the group track. Its own devices, automation lanes, sends and the explicit
    /// outputs pointing at it are **lost** (outputs reset to `Default`): without `force` the
    /// command replies `InvalidState` when any of those exist. One undo step.
    Ungroup {
        group: TrackId,
        force: bool,
    },
    /// Assign a track to a VCA (`None` = unassign). Undoable.
    SetVca {
        id: TrackId,
        vca: Option<TrackId>,
    },
}
