//! Track lifecycle and layout. Mixer controls are in [`crate::mixer`], recording/input in
//! [`crate::recording`].

use serde::{Deserialize, Serialize};
use ts_rs::TS;

use crate::model::{Color, TrackId, TrackKind};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, TS)]
#[serde(tag = "type")]
pub enum TrackCommand {
    /// Create a track with a client-chosen id, placed before `before` (None = last among its
    /// siblings), inside group `parent`. MIDI tracks get no default instrument (the UI
    /// follows up with `Device::Insert` in a `Batch` if it wants one).
    Create {
        id: TrackId,
        kind: TrackKind,
        name: Option<String>,
        color: Option<Color>,
        parent: Option<TrackId>,
        before: Option<TrackId>,
    },
    /// Deletes the track and everything on it (clips, notes, devices, sends to/from it,
    /// lanes). Children of a group are deleted too. The master track cannot be deleted.
    Delete {
        id: TrackId,
    },
    /// Deep copy placed right after the original; child entity ids are generated by the
    /// controller.
    Duplicate {
        id: TrackId,
        new_id: TrackId,
    },
    Rename {
        id: TrackId,
        name: String,
    },
    SetColor {
        id: TrackId,
        color: Color,
    },
    /// Reorder / regroup.
    Move {
        id: TrackId,
        parent: Option<TrackId>,
        before: Option<TrackId>,
    },
    /// Set a MIDI track's piano-roll scale (undoable document edit; never restricts notes).
    SetScale {
        id: TrackId,
        scale: crate::model::TrackScale,
    },
}
