//! TypeScript type export (ts-rs).

use std::path::Path;

use ts_rs::{Config, TS};

use crate::message::{ClientMessage, ServerMessage};
use crate::model::file::EtherFile;
use crate::model::{Op, Transaction};
use crate::plugins::{ScanRequest, ScanResponse};

/// Export every protocol + model type reachable from the root messages into `dir` (one
/// `.ts` file per type) and write an `index.ts` barrel. Existing `.ts` files in `dir` are
/// removed first so deleted types don't linger.
pub fn export_all(dir: &Path) -> Result<(), Box<dyn std::error::Error>> {
    std::fs::create_dir_all(dir)?;
    for entry in std::fs::read_dir(dir)? {
        let path = entry?.path();
        if path.extension().is_some_and(|e| e == "ts") {
            std::fs::remove_file(path)?;
        }
    }

    let cfg = Config::new().with_out_dir(dir);
    ClientMessage::export_all(&cfg)?;
    ServerMessage::export_all(&cfg)?;
    EtherFile::export_all(&cfg)?;
    Op::export_all(&cfg)?;
    Transaction::export_all(&cfg)?;
    ScanRequest::export_all(&cfg)?;
    ScanResponse::export_all(&cfg)?;

    let mut names: Vec<String> = std::fs::read_dir(dir)?
        .filter_map(|e| e.ok())
        .filter_map(|e| e.file_name().into_string().ok())
        .filter(|n| n.ends_with(".ts") && n != "index.ts")
        .map(|n| n.trim_end_matches(".ts").to_string())
        .collect();
    names.sort();
    let mut index =
        String::from("// GENERATED by `just gen-types` from crates/ether-protocol. Do not edit.\n");
    for n in names {
        index.push_str(&format!("export type * from \"./{n}\";\n"));
    }
    std::fs::write(dir.join("index.ts"), index)?;
    Ok(())
}
