[package]
name = "ether-media"
description = "Media decoding, resampling and peak mipmaps."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
ether-core.workspace = true
symphonia.workspace = true
rubato.workspace = true
thiserror.workspace = true

[lints]
workspace = true
